services:
  postgres:
    image: postgres:16-alpine
    container_name: paymate-db
    environment:
      POSTGRES_DB: paymate
      POSTGRES_USER: paymate_user
      POSTGRES_PASSWORD: paymate_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: