-- ================================================================
-- V2__create_users_table.sql
-- Creates users and refresh_tokens tables for Sprint 2 auth system
-- ================================================================

-- ── Users table ──────────────────────────────────────────────────
-- Stores all registered users across all roles (USER, MERCHANT, ADMIN)
-- UUID primary key prevents enumeration attacks (no /users/1, /users/2)
CREATE TABLE users (
    -- UUID generated by PostgreSQL's uuid_generate_v4() function
    -- We enabled this extension in V1__init_schema.sql
    id            UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Email is the primary login identifier, must be globally unique
    email         VARCHAR(255) NOT NULL,

    -- Phone is optional at registration, unique when provided
    phone         VARCHAR(20),

    -- Full name for display purposes
    full_name     VARCHAR(100) NOT NULL,

    -- NEVER store plain text passwords
    -- BCrypt hash always starts with $2a$ and is always 60 chars
    password_hash VARCHAR(255) NOT NULL,

    -- Role controls what the user can do in the system
    -- USER: standard customer, MERCHANT: business, ADMIN: operator
    role          VARCHAR(20)  NOT NULL DEFAULT 'USER',

    -- KYC = Know Your Customer (identity verification)
    -- PENDING: not verified yet, VERIFIED: identity confirmed, REJECTED: failed
    kyc_status    VARCHAR(20)  NOT NULL DEFAULT 'PENDING',

    -- Soft delete: instead of deleting rows, we deactivate
    -- Deleted user data must be kept for financial audit trails
    is_active     BOOLEAN      NOT NULL DEFAULT true,

    -- created_at: when the record was first inserted, never changes
    -- updated_at: changes every time the record is modified
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index on email for fast login lookups
-- Without this index, every login scans the entire users table
CREATE UNIQUE INDEX idx_users_email ON users(email);

-- Index on phone (partial: only rows where phone is not null)
-- No point indexing NULL values
CREATE UNIQUE INDEX idx_users_phone ON users(phone)
    WHERE phone IS NOT NULL;


-- ── Refresh tokens table ──────────────────────────────────────────
-- Stores refresh tokens so users can get new access tokens
-- without logging in again, and so we can revoke sessions (logout)
CREATE TABLE refresh_tokens (
    id          UUID         PRIMARY KEY DEFAULT uuid_generate_v4(),

    -- Which user owns this refresh token
    user_id     UUID         NOT NULL REFERENCES users(id),

    -- We store the HASH of the token, not the token itself
    -- If this table is compromised, attackers can't use the hashes
    token_hash  VARCHAR(255) NOT NULL UNIQUE,

    -- When this token stops working, even if not revoked
    expires_at  TIMESTAMP    NOT NULL,

    -- Set to true on logout — even non-expired tokens won't work
    revoked     BOOLEAN      NOT NULL DEFAULT false,

    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for fast token lookup during refresh requests
CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);